### PR TITLE
Feature/input validation

### PR DESCRIPTION
**Pull request by nickfryar**

### CODE REVIEW

**Review by BiermanM — CHANGES_REQUESTED** [review]
Use a darker shade of green for the valid inputs

Submit button should be disabled if not all required fields are filled out (cursor should have the disabled styling and the button should look disabled (and also not change state when hovered over)

**Comment by nickfryar** [comment]
> Use a darker shade of green for the valid inputs
> 
> Submit button should be disabled if not all required fields are filled out (cursor should have the disabled styling and the button should look disabled (and also not change state when hovered over)

@BiermanM Do you mean the style shouldn't change on hover for the Submit button? Because I think the :hover style is set in one of the template css files, but I'm not able to find it.

Also, I've disabled the Submit button until the fields are validated, but now there's only one instance that the field colors change: if the email field isn't empty but isn't formatted correctly (e.g. mail@example.com), the Submit button is enabled - the the other fields are marked green when the Submit button is clicked. Is this what you're wanting?

**Comment by BiermanM** [comment]
Well the style should only not change upon hovering over the button if the button's disabled, but if changing the :hover is too difficult, we can ignore it.

Here's some things I've noticed that need to be fixed, and I think these will answer your question:

1. The submit button should become enabled only when Full Name is not empty, Message is not empty, and Email has a valid email syntax.
2. If the user tries to click the submit button while it's disabled, the "Please fill out all required fields." alert should appear and all invalid inputs should be red (and if any valid inputs exist, make them green).
3. If the user types something into all 3 required fields, but then erases their content in one of the required fields before clicking the submit button, the submit button is still enabled (it should be disabled again at that point).

**Comment by nickfryar** [comment]
@BiermanM Just in case it didn't notify you, I updated the logic for the submit button

**Pull request merged**
